blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    #숫자형태의 url이 들어온다.
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    # localhost:8080/comment/5/approve
    path('comment/<int:pk>/approve', views.comment_approve, name='comment_approve'),
    # localhost:8080/comment/5/remove
    path('comment/<int:pk>/remove', views.comment_remove, name='comment_remove'),

]

config/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('login/$', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/$', LoginView.as_view(), name='logout', kwargs={'next_page': '/'}),

]

polls/urls.py
from django.urls import path
from . import views

from django.conf.urls import *
from polls.views import PollFeed
from django.contrib import admin
admin.autodiscover()

app_name = 'polls'

urlpatterns=[
    path('',views.IndexView.as_view(),name='index'), #인덱스 첫 메인 polls
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # path('<int:pk>/full/', views.FullResultsView.as_view(), name='full'),
    path('<int:pk>/fullre/', views.FullResultsView.as_view(), name='fullre'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

polls/models.py
import datetime

from django import forms
from django.db import models
from django.forms import formset_factory
from django.utils import timezone
from django.conf import settings
from django.shortcuts import render

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now()-datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean =True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text



class Survey(models.Model):
    title = models.CharField(max_length=200)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='surveys'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class SurveyAssignment(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    survey = models.ForeignKey(
        Survey,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='survey_assignments'
    )
    assigned_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='assigned_surveys_to'
    )
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='assigned_surveys'
    )


class SurveyResponse(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    survey_assigned = models.ForeignKey(
        SurveyAssignment,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='survey_responses'
    )
    question = models.ForeignKey(
        Question,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='question_responses'
    )
    choice = models.ForeignKey(
        Choice,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='choices_selected'
    )

polls/forms.py
from datetime import datetime

from django import forms
from .models import Question

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question_text','pub_date',)


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, reverse
from django.views import View

from .forms import QuestionForm
from .models import Question, Choice
from django.template import loader
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
from django.http import Http404
from django.views import generic
from django.utils import timezone

import json
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User, Group, Permission
from django.core.exceptions import ValidationError
from django.db import transaction
from django.db.models import Q
from django.shortcuts import render, redirect, reverse, get_object_or_404

from django.views import View

from .models import Survey, Question, Choice, SurveyAssignment, SurveyResponse

import datetime
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from polls.forms import RenewBookForm


class QuestionViewModel:
    def __init__(self, text, choices=[]):
        self.text = text
        self.choices = choices

    def add_survey_response(self, survey_response):
        for choice in self.choices:
            if choice.id == survey_response.choice.id:
                choice.responses += 1
                break


class ChoiceResultViewModel:
    def __init__(self, id, text, responses=0):
        self.id = id
        self.text = text
        self.responses = responses


def question_list(request):
    questions = Question.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'polls/index.html', {'questions': questions})

def question_detail(request, pk):
    question = get_object_or_404(Question, pk=pk)
    return render(request, 'polls/detail.html', {'question': question})

def question_new(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.published_date = timezone.now()
            question.save()
            return redirect('polls:detail', pk=question.pk)
        #GET request.method가 오면
    else:
        form = QuestionForm()
        return render(request, 'polls/full_result.html', {'form': form})

# Create your views here.
class IndexView(generic.ListView): #()인자안에 부모 클래스가 들어감
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    """Return the last five published questions."""
    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

class FullResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/full_result.html'


def vote(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request,'polls/detail.html',{
            'questions':question,
            'error_message':"You didn't select a choice",
        })
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class PollFeed(generic.DetailView):
    title = "Polls"
    link = "/polls"
    description = "Latest Polls"

    def items(self):
        return Question.objects.all().order_by('-pub_date')

    def item_link(self, poll):
        return reverse('polls:detail', args=(poll.id,))

    def item_pubdate(self, poll):
        return poll.pub_date


class RegisterView(View):
    def get(self, request):
        return render(request, 'polls/register.html', { 'form': UserCreationForm() })

    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect(reverse('login'))

        return render(request, 'polls/register.html', { 'form': form })

polls/templates/polls/detail.html
{% extends 'base.html' %}
{% block title %} detail.html{% endblock %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{% block content %}
<h1>{{question.question_text}}</h1>
{% if error_message %}<p><strong>{{error_message}}</strong></p> {% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type = "radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for = "choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>
{% endblock %}

polls/templates/polls/full_result.html
{% extends 'base.html' %}
{% block title %} full_result.html{% endblock %}

{% block content %}

<div><h3>Poll Result</h3>
    <p></p>
        <ol>
            <div class="question">
            <li style="padding-bottom: 25px;">
              <p>{{question.question_text}}</p>
              <div style="margin-left: 30px;">
                <table class='table'>

                  <thead>
                    <tr>
                      <td>CHOICE</td>
                      <td>POLLSRESPONES</td>
                    </tr>
                  </thead>
                  <tbody>
                    {% for choice in question.choice_set.all %}
                    <tr>
                      <td>{{ choice.choice_text }}</td>
                      <td>{{ choice.votes }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </li>
            </div>
          </ol>
    </div>
{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}

    <ul>
        {% for question in latest_question_list %}

            <li>
                <a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a>
            </li>
            <li>
                <a href="{% url 'polls:fullre' question.id %}">전체 투표 결과보기</a>
            </li>
        {% endfor %}
    </ul>

{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends 'base.html' %}
{% block title %} results.html{% endblock %}

{% block content %}
<h1>{{question.question_text}}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}