blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    #숫자형태의 url이 들어온다.
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    # localhost:8080/comment/5/approve
    path('comment/<int:pk>/approve', views.comment_approve, name='comment_approve'),
    # localhost:8080/comment/5/remove
    path('comment/<int:pk>/remove', views.comment_remove, name='comment_remove'),

]

bookmark/urls.py
from django.urls import path
from .views import BookmarkListView, BookmarkCreateView
from .views import BookmarkListView, BookmarkCreateView, BookmarkDetailView,BookmarkUpdateView, BookmarkDeleteView

app_name = 'bookmark'

urlpatterns = [
    path('', BookmarkListView.as_view(), name='list'),
    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('detail/<int:pk>/', BookmarkDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BookmarkDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('login/$', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/$', LoginView.as_view(), name='logout', kwargs={'next_page': '/'}),

]

home/urls.py
from django.urls import path
from .import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

polls/urls.py
from django.urls import path
from . import views

from django.conf.urls import *
from polls.views import PollFeed
from django.contrib import admin
admin.autodiscover()

app_name = 'polls'

urlpatterns=[
    path('',views.IndexView.as_view(),name='index'), #인덱스 첫 메인 polls
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # path('<int:pk>/full/', views.FullResultsView.as_view(), name='full'),
    path('<int:pk>/fullre/', views.FullResultsView.as_view(), name='fullre'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django import forms

# Create your models here.
#포스트라는 '테이블 정의' 중
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True,null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self): return self.title

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Post, Comment

def min_length_3_validator(value):
    if len(value) < 3:
        raise forms.ValidationError('title은 3글자 이상 입력해주세요')


class PostForm(forms.Form):
    # title = forms.CharField()
    title = forms.CharField(validators=[min_length_3_validator])
    text = forms.CharField(widget=forms.Textarea)

class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.utils import timezone
from django.contrib.auth.models import User
from .models import Post,Comment
from .forms import PostForm, PostModelForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView

#함수형 뷰의 매개변수로는 request로 받음
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date').order_by('-created_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

@login_required
def post_new(request):
    if request.method == "POST":
        # Form 데이터를 입력하고 등록요청 시 보여주는 부분
        form = PostForm(request.POST)
        # Form 데이터가 clean 한 상태
        if form.is_valid():
            # PostForm 으로 저장하는 법
            print(form.cleaned_data)
            post = Post.objects.create(author=User.objects.get(username=request.user),
                                       published_date=timezone.now(),
                                       title=form.cleaned_data['title'],
                                       text=form.cleaned_data['text'])
            # Post ModelForm 으로 저장하는 법
            # title, text 필드의 값이 저장된다.
            # post = form.save(commit=False)
            # post.author = User.objects.get(username=request.user)
            # post.published_date = timezone.now()
            # DB에 등록됨
            # post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        # 등록 Form 보여주는 부분
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostModelForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = User.objects.get(username=request.user)
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostModelForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})


def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:post_list')

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail', pk=post_pk)

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}
{% block content %}
    <table>
        <h1>New Comment</h1>
        <form method="POST" class="post-form">
            {% csrf_token %}
            <table class="table table-bordered table-hover">
                {{form.as_table}}
            </table>
            <button type="submit" class="save btn btn-default">Send</button>
        </form>
    </table>
{% endblock%}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'blog/boot320.css' %}">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>

<div class="container">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand1" href="{% url 'home:home' %}"> Marie's Page </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'home:home' %}">Home<span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'polls:index' %}">Polls <span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'bookmark:list' %}">Bookmark <span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:post_list' %}">Blog <span class="sr-only"></span></a>
          </li>
        </ul>
      </div>
    </nav>

<div class="page-header">
        {% if user.is_authenticated %}
            <a href="{% url 'blog:post_new' %}" class="top-menu">
                <span class="glyphicon glyphicon-plus"></span>
            </a>
            <p class="top-menu">Hello {{user.username}}
            <small>(<a href="{% url 'logout' %}?next={{request.path}}">Logout</a>)</small></p>
        {% else %}
            <a href="{% url 'login' %}" class="top-menu">
                <span class="glyphicon glyphicon-lock"></span>
            </a>
        {% endif %}
        <h1><a href="{% url 'blog:post_list' %}">Marie's Blog</a></h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>


    {% comment "Optional note" %}
        Server comment
    {% endcomment %}
    <!-- html Client Comment -->
</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block title %}
{% endblock %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
            <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
            <a class="btn btn-default" href="{% url 'blog:post_remove' pk=post.pk %}">Delete</a>

        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
                {% if user.is_authenticated %}
        {% endif %}
    </div>

<hr>
<h2>
<a class="btn btn-default" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add comment</a>
</h2>
{% for comment in post.comments.all %}
    {% if user.is_authenticated or comment.approved_comment %}
        <div class="comment">
            <div class="date">
                {{comment.created_date}}
            </div>
            <strong>{{comment.author}}</strong>
            <p>{{comment.text|linebreaks}}</p>
            {% if not comment.approved_comment %}
                    <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}">
                        <span>Remove</span>
                    </a>
                    <a class="btn btn-default" href="{% url 'blog:comment_approve' pk=comment.pk %}">
                        <span>Approve</span>
                    </a>
                {% endif %}
        </div>
    {% endif %}
{% empty %}
    <p>No comment here yet :(</p>
{% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% block content %}
  <h1>New post</h1>
  <form method="POST" class="post-form">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
  </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block title %}
{% endblock %}

{% block content %}
    {% for post in posts %}
            <div class="post">
                <div class="date">
                    <p>published: {{ post.published_date }}</p>
                </div>
                <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
                <p>{{ post.text|linebreaksbr }}</p>
                <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.comments.count }}</a>
            </div>
    {% endfor %}
{% endblock %}